### PR TITLE
Install windows service on deploy when it is missing

### PR DESCRIPTION
**Pull request by akselsson**
This is a work in progress attempt to give Asimov capability to install services when they are missing on the unit.

This pull request is more a request for feedback than a production ready feature, so don't merge yet.

But please leave feedback.

### CODE REVIEW

**Comment by mullvaden** [comment]
I like it, this is what we were seeing as the next step when digging around in the code.

But should we lean on powershell when installing or probe some windows apis to do the install , in the same way the update is done? Maybe the ps1-approach will do, and is faster to implement. But wouldn't it be nicer if agent only gets config stuff, and the agent knows the heavy lifting in the operating system.

**Comment by akselsson** [comment]
Funderar på formatet för configfilen. Man kan antingen göra det som en del av service, typ:
```
"Units": [
    {
      "Name": "Asimov.Roundhouse.Example",
      "Type": "WindowsService",
      
      "TargetPath": "%DATA_FOLDER%\\WindowsServiceTarget",
      
      "DeployParameters": {
        "NotUsed": { "Type": "Text" }
      },
      
      "InstallCommand":  ".\\Asimov.Roundhouse.Example.exe install -displayname \"$DisplayName\""
      "InstallParameters": {
        "DisplayName": {
          "Type": "Text",
          Default: "Asimov Test Service From Config"
        }
      },
      
      "UninstallCommand": ".\\Asimov.Roundhouse.Example.exe uninstall",

      "PackageInfo": { "Source": "Test" }
    }
  ]
```

Alternativt så gör man installation till ett egen sektion:
```
"Units" : [
      {
         "Name": "Api.Push",
         "Type": "WindowsService",

         "PackageInfo": { 
            "Source": "Builds",
            "InternalPath":  "Api.Push"
          },

          "DeployParameters": {
              "NotUsed": { "Type": "Text" }
          },

         "Installable" : {
            "TargetPath": "c:\\temp\\service",
            "Install": ".\\Test.Roundhouse.exe install -username:$Username -password:$Password",
            "InstallParameters": {
               "Username": { "Type": "Text", Default: "domain\\user"},
               "Password": { "Type": "Password"}
            },
            "Uninstall": ".\\Test.Roundhouse.exe uninstall"
         }  
      }
   ]
```
Fördelen med den senare är att det blir lättare att föra över till andra typer av enheter (t.ex. WebSite). Man skulle nog kunna extrahera Installable som en dekorator som man kan lägga runt alla enheter. Nackdelen är att det blir mer konfig.

Tankar?

**Comment by marefr** [comment]
Think it's a great first step towards giving asimov power to install services. Here comes some random thoughts and questions, please bare with me. I have not looked into detail of the provided code Patrik @akselsson, but more into your provided config examples. 

I maybe see another config alternative and that are to use the existing structure for UnitActions, but I have no idea if that will work or make life easier. It would however follow start/stop/verify Actions, e.g:

```json
"Units" : 
[
  {
    "Name": "Test.RoundHouse",
    "Type": "WindowsService",

    "PackageInfo": { 
      "Source": "Builds",
      "InternalPath":  "Api.Push"
    },

    "Actions": {
      "Install": {
        "Type": "InstallCommand",
        "InstallParameters": {
          "Username": { "Type": "Text", "Default": "domain\\user" },
          "Password": { "Type": "Password" }
        },
        "Command": ".\\Test.Roundhouse.exe install -username:$Username -password:$Password"
      },
      "Uninstall": {
        "Type": "UninstallCommand",
        "UninstallParameters": {
          "Username": { "Type": "Text", "Default": "domain\\user" },
          "Password": { "Type": "Password" }
        },
        "Command": ".\\Test.Roundhouse.exe uninstall"
      }
    }
  }
]
```

On a second thought stop/start actions are automatically created for windows services and websites so maybe install/uninstall action should be created automatically if windows services or website have one of your 2 provided configs above? 

Using the existing UnitAction structure would however allow actions (buttons) for install/uninstall in Asimov UI, but don't know if that's good or needed at all if it automatically installs a service if not installed during deploy? My idea is that a specific install command/button would prompt you for parameters etc, but as you described to me face-to-face your intents are to depend on if a service is installed or not and depending on what you can use different behaviours. After thinking of this I think you're on the right track, there shouldn't be any difference between installing or deploying a service.

Overall, I think that you have thought this through more than any of us at the moment and whatever solution we choose it will solve our biggest problem, installing new services. Websites etc is something that we could look into later on.

**Comment by akselsson** [comment]
Tror att jag valde att koppla det till deploy istället för unit actions
eftersom man i deploy väljer en version att driftsätta. Det går säkert att
göra i en unit action också men det skulle bli mer jobb i asimov-frontend.

**Pull request merged**
